APP_ENV=local
APP_DEBUG=true
APP_KEY=0jPkG1AXVIM5bNnQyKNrENUWkK9Jcn43

DB_HOST=127.0.0.1
DB_DATABASE=docsearch
DB_USERNAME=root
DB_PASSWORD=123456

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

ES_HOST=dev.elasticsearch.com:9200

EBT_FILE_STORAGE=/var/www/es_docs
